name: Upload Coverage Report

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout codecov.yml
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /.github/.codecov.yml
            /.github/codecov.yml
            /dev/.codecov.yml
            /dev/codecov.yml
            /.codecov.yml
            /codecov.yml
          sparse-checkout-cone-mode: false
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          pattern: codecov.json
          run-id: ${{ github.event.workflow_run.id }}
      - name: Find associated pull request
        uses: actions/github-script@v7
        if: github.event.workflow_run.event == 'pull_request'
        id: pr
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} is:pr sha:${context.payload.workflow_run.head_sha}`,
              per_page: 1,
            });
            const items = response.data.items;
            if (items.length < 1) {
              console.error('No PRs found');
              return;
            }
            const pullRequestNumber = items[0].number;
            console.info("Pull request number is", pullRequestNumber);
            return pullRequestNumber;
      - name: debug
        env:
          GITHUB_DATA: ${{ toJson(github) }}
          JOB_DATA: ${{ toJson(job) }}
        run: 'printf "github:\n%s\njob:\n%s\n" "$GITHUB_DATA" "$JOB_DATA"'
#      - uses: codecov/codecov-action@v4
#        if: hashFiles('codecov.json')
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          job_code: ${{ github.event.workflow.name }}
#          override_branch: ${{ github.event.workflow_run.head_branch }}
#          override_build: ${{ github.event.workflow_run.id }}
#          override_commit: ${{ github.event.workflow_run.head_sha }}
#          override_pr: ${{ steps.pr.outputs.result }}
